name: Build x86_64-darwin

on:
    workflow_call:
        inputs:
            cache-key:
                type: string
                required: false
                default: x86_64-darwin-artifacts-${{ github.sha }}

jobs:
    build-x86_64-darwin:
        name: Build x86_64 Darwin
        runs-on: macos-13-large
        concurrency: ${{ inputs.cache-key }}
        permissions:
            id-token: "write"
            contents: "read"
        steps:
            - uses: actions/checkout@v4
            - uses: DeterminateSystems/nix-installer-action@main
            - uses: DeterminateSystems/magic-nix-cache-action@main
            - name: Build the installer
              run: make ci.x86_64-darwin
            - name: Create GitHub cache
              uses: actions/cache/save@v3
              with:
                    path: build
                    key: ${{ inputs.cache-key }}