name: Build x86_64-inux

on:
  workflow_call:
        inputs:
            cache-key:
                    type: string
                    required: false
                    default: x86_64-linux-artifacts-${{ github.sha }}

jobs:
    build-x86_64-linux:
        name: Build x86_64 Linux (static)
        runs-on: UbuntuLatest32Cores128G
        concurrency: ${{ inputs.cache-key }}
        permissions:
            id-token: "write"
            contents: "read"
        steps:
            - uses: actions/checkout@v4
            - uses: DeterminateSystems/nix-installer-action@main
            - uses: DeterminateSystems/magic-nix-cache-action@main
            - name: Build the installer
              run: make ci.x86_64-linux
            - name: Create GitHub cache from build artifacts
              uses: actions/cache/save@v3
              with:
                    path: build
                    key: ${{ inputs.cache-key }}