name: Release

concurrency:
    group: release

on:
    push:
        tags:
            - "v*.*.*"

permissions:
    contents: write

jobs:
    build-x86_64-linux: { uses: ./.github/workflows/build-x86_64-linux.yml }
    build-x86_64-darwin: { uses: ./.github/workflows/build-x86_64-darwin.yml }
    build-aarch64-linux: { uses: ./.github/workflows/build-aarch64-linux.yml }
    build-aarch64-darwin: { uses: ./.github/workflows/build-aarch64-darwin.yml }
    
    release:
        runs-on: ubuntu-latest
        needs:
            - build-x86_64-linux
            - build-x86_64-darwin
            - build-aarch64-linux
            - build-aarch64-darwin
        steps:
            - uses: actions/checkout@v4
            - name: Create artifacts directory
              run: mkdir -p ./artifacts
    
            - uses: actions/cache/restore@v3
              name: Restore x86_64-linux artifacts
              with:
                path: build
                key: x86_64-linux-artifacts-${{ github.sha }}
            - name: Move x86_64-linux artifacts
              run: mv ./build ./artifacts/x86_64-linux
    
            - uses: actions/cache/restore@v3
              name: Restore x86_64-darwin artifacts
              with:
                path: build
                key: x86_64-darwin-artifacts-${{ github.sha }}
            - name: Move x86_64-darwin artifacts
              run: mv ./build ./artifacts/x86_64-darwin
    
            - uses: actions/cache/restore@v3
              name: Restore aarch64-linux artifacts
              with:
                path: build
                key: aarch64-linux-artifacts-${{ github.sha }}
            - name: Move aarch64-linux artifacts
              run: mv ./build ./artifacts/aarch64-linux
    
            - uses: actions/cache/restore@v3
              name: Restore aarch64-darwin artifacts
              with:
                path: build
                key: aarch64-darwin-artifacts-${{ github.sha }}

            - name: Publish Release to GitHub
              uses: softprops/action-gh-release@v1
              with:
                fail_on_unmatched_files: true
                draft: true
                files: |
                    artifacts/**